In [5]:
import numpy as np
lst = [1, 2, 3, 4]
print(lst)
print(type(lst))
print("-" * 30)

s = np.array(5)
print(s)
print("-" * 30)

v = np.array([1, 2, 3, 4])
print(v)
print("-" * 30)

m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(m)
            

[1, 2, 3, 4]
<class 'list'>
------------------------------
5
------------------------------
[1 2 3 4]
------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print("="*30)
s = np.array(5)
# print(s)
print(s.ndim)
print(s.shape)

print("="*30)

v = np.array([1,2,3,4])
# print(v)
print(v.ndim)
print("="*30)
print(m.ndim)
print(m.shape)

0
()
1
2
(3, 3)


In [10]:
vec = np.array([1,2,3,4,5,6])
mat = vec.reshape((3,2))
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
vec = np.array([1,2,3,4,5,6])
print(v)
vec.shape
#mat = vec.reshape((3,2))
#mat

(6,)

In [18]:
vec = np.array([1,2,3,4])
v2 = vec.reshape(vec.shape[0],1)
v2


array([[1],
       [2],
       [3],
       [4]])

In [19]:
vec = np.array([1,2,3,4])
mat = vec[:,None]
mat

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
lst = [1,2,3]

In [22]:
def array_reshape(arr, rows , cols):
    try:
        arr = np.array(arr)
        return arr.reshape(rows, cols)
    except (TypeError, ValueError) as e:
        raise ValueError(f"Invalid reshape operatetion: {e}")
    except (TypeError, ValueError) as s:
        raise ValueError(f"Invalid reshape operatetion: {s}")

In [29]:
mat = np.array([[1.1,'2',3],
               [4,5,6],
               [7,8,9]]
               )
print(mat.dtype)
print(mat)

<U32
[['1.1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]


In [33]:
mat = np.array([[1,2,"2"],
               [4,5,6],
               [7,8,9]]
               )
fmat = mat.astype(int)
print(fmat)
print(fmat.dtype)

[[1 2 2]
 [4 5 6]
 [7 8 9]]
int64


In [34]:
def convert_dtype(arr,dtype):
    try:

        arr = np.array(arr)
        return arr.astype(dtype)
    except TypeError as e:
        raise TypeError(f"Invalid target data type :{dtype}") from e

In [ ]:
v = np.array

In [37]:
mat = np.array([[1,2,2],
               [4,5,6],
               [7,8,9],
               [0,0,0]]
               )
mat[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [39]:
mat = np.array([[1,2,"2"],
               [4,5,6],
               [7,8,9]]
               )
mat.T

array([['1', '4', '7'],
       ['2', '5', '8'],
       ['2', '6', '9']], dtype='<U21')

In [40]:
mat = np.zeros((3,4))
mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
mat = np.ones((3,4))
mat

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
mat = np.full((3,4),6)
mat

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [45]:
def init_arr(shape, value =0):
    return np.full(shape, value)

In [46]:
zeros = init_arr((3,4))
zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])